---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: default
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "mlnx_bf",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["a2d3", "101e"]
                }
            }
        ]
    }

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-device-plugin
  namespace: default

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sriov-device-plugin
  namespace: default
  labels:
    tier: node
    app: sriovdp
spec:
  selector:
    matchLabels:
      name: sriov-device-plugin
  template:
    metadata:
      labels:
        name: sriov-device-plugin
        tier: node
        app: sriovdp
    spec:
      hostNetwork: true
      nodeSelector:
        network.operator.openshift.io/external-openvswitch: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: sriov-device-plugin
      containers:
      - name: sriovdp
        image: quay.io/zshi/sriov-device-plugin:bluefield
        imagePullPolicy: IfNotPresent
        args:
        - --log-level=10
        - --resource-prefix=openshift.io
        securityContext:
          privileged: true
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/
          readOnly: false
        - name: log
          mountPath: /var/log
        - name: config-volume
          mountPath: /etc/pcidp
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/
        - name: log
          hostPath:
            path: /var/log
        - name: config-volume
          configMap:
            name: sriovdp-config
            items:
            - key: config.json
              path: config.json
