---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: default
  namespace: default
spec:
        config: '{"cniVersion":"0.3.1","name":"ovn-kubernetes","type":"ovn-k8s-cni-smart-nic","kubeconfig":"/etc/kubernetes/cni/net.d/multus.d/multus.kubeconfig","logFile":"/var/log/ovn-kubernetes/ovn-k8s-smart-nic-cni.log","logLevel":"4","ipam":{},"dns":{}}'
