apiVersion: v1
kind: Pod
metadata:
  name: pod-bf
  annotations:
    v1.multus-cni.io/default-network: default/default
spec:                                                                
  containers:
  - name: appcntr1
    image: quay.io/zshi/centos:iperf
    command: ['/bin/sh', '-c', 'sleep infinity']
    resources:
      requests:
        openshift.io/mlnx_bf: '1'
      limits:
        openshift.io/mlnx_bf: '1'
